services:

  gui-app:
    container_name: gui-app
    build:
      context: /gui
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: "local"
      DISPLAY: "${DISPLAY}"
    networks:
      - app-network
    ports:
      - 5000:5000
    depends_on:
      - scraper-app
    # keep the container up and running, so we can exec into it
    command:
      tail -f /dev/null
    volumes:
      - ./gui/:/app
      - /tmp/.X11-unix:/tmp/.X11-unix

  scraper-app:
    container_name: scraper-app
    build:
      context: /scraper
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: "local"
    networks:
      - app-network
    depends_on:
      - postgres_db
    # keep the container up and running, so we can exec into it
    command:
      tail -f /dev/null
      # bash -c "pipenv run python main.py"
    volumes:
      - ./scraper/:/app

  postgres_db:
    container_name: container-pg
    image: postgres
    hostname: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  analizer-app:
    container_name: analizer-app
    build:
      context: /analizer
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: "local"
    networks:
      - app-network
    ports:
      - 5001:5001
    depends_on:
      - scraper-app
      - postgres_db
    # keep the container up and running, so we can exec into it
    command:
      tail -f /dev/null
    volumes:
      - ./analizer/:/app

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: