services:

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: "local"
      DISPLAY: "${DISPLAY}"
    networks:
      - app-tier
    # keep the container up and running, so we can exec into it
    command:
      tail -f /dev/null
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  app-tier:
    driver: bridge